Name: Settings
Type: FolderType
Children:
- Name: AnalogVariable3
  Type: AnalogItemType
  DataType: Float
  DisplayName: {"NamespaceIndex":28,"TextId":"Option"}
  Value: 0.27000001072883606
  Children:
  - Name: EURange
    Type: RangeType
    DataType: Range
    Children:
    - Name: Low
      Type: BaseVariableType
      DataType: Double
      ReferenceType: HasProperty
    - Name: High
      Type: BaseVariableType
      DataType: Double
      ReferenceType: HasProperty
      Value: 1.0
  - Name: EngineeringUnits
    Type: EUInformationType
    DataType: EUInformation
    Children:
    - Name: UnitId
      Type: BaseVariableType
      DataType: Int32
      ReferenceType: HasProperty
      Value: 5066817
    - Name: DisplayName
      Type: BaseVariableType
      DataType: LocalizedText
      ReferenceType: HasProperty
    - Name: Description
      Type: BaseVariableType
      DataType: LocalizedText
      ReferenceType: HasProperty
- Name: AnalogVariable2
  Type: AnalogItemType
  DataType: Float
  DisplayName: {"NamespaceIndex":28,"TextId":"Cleaning"}
  Value: 0.11999999731779099
  Children:
  - Name: EURange
    Type: RangeType
    DataType: Range
    Children:
    - Name: Low
      Type: BaseVariableType
      DataType: Double
      ReferenceType: HasProperty
    - Name: High
      Type: BaseVariableType
      DataType: Double
      ReferenceType: HasProperty
      Value: 0.2
  - Name: EngineeringUnits
    Type: EUInformationType
    DataType: EUInformation
    Children:
    - Name: UnitId
      Type: BaseVariableType
      DataType: Int32
      ReferenceType: HasProperty
      Value: 5066817
    - Name: DisplayName
      Type: BaseVariableType
      DataType: LocalizedText
      ReferenceType: HasProperty
    - Name: Description
      Type: BaseVariableType
      DataType: LocalizedText
      ReferenceType: HasProperty
- Name: AnalogVariable1
  Type: AnalogItemType
  DataType: Float
  DisplayName: {"NamespaceIndex":28,"TextId":"Vacuum"}
  Children:
  - Name: EURange
    Type: RangeType
    DataType: Range
    Children:
    - Name: Low
      Type: BaseVariableType
      DataType: Double
      ReferenceType: HasProperty
      Value: -100.0
    - Name: High
      Type: BaseVariableType
      DataType: Double
      ReferenceType: HasProperty
  - Name: EngineeringUnits
    Type: EUInformationType
    DataType: EUInformation
    Children:
    - Name: UnitId
      Type: BaseVariableType
      DataType: Int32
      ReferenceType: HasProperty
      Value: 4935745
    - Name: DisplayName
      Type: BaseVariableType
      DataType: LocalizedText
      ReferenceType: HasProperty
    - Name: Description
      Type: BaseVariableType
      DataType: LocalizedText
      ReferenceType: HasProperty
